<?php
/**
 * PlanLimits
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PlanLimits Class Doc Comment
 *
 * @category Class
 * @description Per-plan numeric limits. &#x60;-1&#x60; in any field means unlimited.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PlanLimits implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PlanLimits';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'max_connectors' => 'int',
        'max_invoices_per_month' => 'int',
        'max_users' => 'int',
        'metered' => 'array<string,int>',
        'paid_connectors' => 'string[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'max_connectors' => 'int32',
        'max_invoices_per_month' => 'int64',
        'max_users' => 'int32',
        'metered' => 'int64',
        'paid_connectors' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'max_connectors' => false,
        'max_invoices_per_month' => false,
        'max_users' => false,
        'metered' => false,
        'paid_connectors' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'max_connectors' => 'maxConnectors',
        'max_invoices_per_month' => 'maxInvoicesPerMonth',
        'max_users' => 'maxUsers',
        'metered' => 'metered',
        'paid_connectors' => 'paidConnectors'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'max_connectors' => 'setMaxConnectors',
        'max_invoices_per_month' => 'setMaxInvoicesPerMonth',
        'max_users' => 'setMaxUsers',
        'metered' => 'setMetered',
        'paid_connectors' => 'setPaidConnectors'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'max_connectors' => 'getMaxConnectors',
        'max_invoices_per_month' => 'getMaxInvoicesPerMonth',
        'max_users' => 'getMaxUsers',
        'metered' => 'getMetered',
        'paid_connectors' => 'getPaidConnectors'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('max_connectors', $data ?? [], null);
        $this->setIfExists('max_invoices_per_month', $data ?? [], null);
        $this->setIfExists('max_users', $data ?? [], null);
        $this->setIfExists('metered', $data ?? [], null);
        $this->setIfExists('paid_connectors', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['max_connectors'] === null) {
            $invalidProperties[] = "'max_connectors' can't be null";
        }
        if ($this->container['max_invoices_per_month'] === null) {
            $invalidProperties[] = "'max_invoices_per_month' can't be null";
        }
        if ($this->container['max_users'] === null) {
            $invalidProperties[] = "'max_users' can't be null";
        }
        if ($this->container['paid_connectors'] === null) {
            $invalidProperties[] = "'paid_connectors' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets max_connectors
     *
     * @return int
     */
    public function getMaxConnectors()
    {
        return $this->container['max_connectors'];
    }

    /**
     * Sets max_connectors
     *
     * @param int $max_connectors max_connectors
     *
     * @return self
     */
    public function setMaxConnectors($max_connectors)
    {
        if (is_null($max_connectors)) {
            throw new \InvalidArgumentException('non-nullable max_connectors cannot be null');
        }
        $this->container['max_connectors'] = $max_connectors;

        return $this;
    }

    /**
     * Gets max_invoices_per_month
     *
     * @return int
     */
    public function getMaxInvoicesPerMonth()
    {
        return $this->container['max_invoices_per_month'];
    }

    /**
     * Sets max_invoices_per_month
     *
     * @param int $max_invoices_per_month max_invoices_per_month
     *
     * @return self
     */
    public function setMaxInvoicesPerMonth($max_invoices_per_month)
    {
        if (is_null($max_invoices_per_month)) {
            throw new \InvalidArgumentException('non-nullable max_invoices_per_month cannot be null');
        }
        $this->container['max_invoices_per_month'] = $max_invoices_per_month;

        return $this;
    }

    /**
     * Gets max_users
     *
     * @return int
     */
    public function getMaxUsers()
    {
        return $this->container['max_users'];
    }

    /**
     * Sets max_users
     *
     * @param int $max_users max_users
     *
     * @return self
     */
    public function setMaxUsers($max_users)
    {
        if (is_null($max_users)) {
            throw new \InvalidArgumentException('non-nullable max_users cannot be null');
        }
        $this->container['max_users'] = $max_users;

        return $this;
    }

    /**
     * Gets metered
     *
     * @return array<string,int>|null
     */
    public function getMetered()
    {
        return $this->container['metered'];
    }

    /**
     * Sets metered
     *
     * @param array<string,int>|null $metered metered
     *
     * @return self
     */
    public function setMetered($metered)
    {
        if (is_null($metered)) {
            throw new \InvalidArgumentException('non-nullable metered cannot be null');
        }
        $this->container['metered'] = $metered;

        return $this;
    }

    /**
     * Gets paid_connectors
     *
     * @return string[]
     */
    public function getPaidConnectors()
    {
        return $this->container['paid_connectors'];
    }

    /**
     * Sets paid_connectors
     *
     * @param string[] $paid_connectors Connectors that are *not* included in this plan (require a higher tier). Empty = all connectors included on this plan.
     *
     * @return self
     */
    public function setPaidConnectors($paid_connectors)
    {
        if (is_null($paid_connectors)) {
            throw new \InvalidArgumentException('non-nullable paid_connectors cannot be null');
        }
        $this->container['paid_connectors'] = $paid_connectors;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


