<?php
/**
 * PlatformInfo
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PlatformInfo Class Doc Comment
 *
 * @category Class
 * @description Public metadata for one registered plugin (admin UI). Maps 1:1 from [&#x60;plugin_core::PluginInfo&#x60;] (same field shape as before).
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PlatformInfo implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PlatformInfo';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'author' => 'string',
        'changelog' => '\OpenAPI\Client\Model\ChangelogEntry[]',
        'config_field_names' => 'string[]',
        'config_fields' => '\OpenAPI\Client\Model\ConfigFieldInfo[]',
        'display_name' => 'string',
        'platform' => 'string',
        'pricing' => '\OpenAPI\Client\Model\PluginPricing',
        'supported_entities' => 'string[]',
        'supports_export' => 'bool',
        'supports_import' => 'bool',
        'supports_oauth' => 'bool',
        'version' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'author' => null,
        'changelog' => null,
        'config_field_names' => null,
        'config_fields' => null,
        'display_name' => null,
        'platform' => null,
        'pricing' => null,
        'supported_entities' => null,
        'supports_export' => null,
        'supports_import' => null,
        'supports_oauth' => null,
        'version' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'author' => false,
        'changelog' => false,
        'config_field_names' => false,
        'config_fields' => false,
        'display_name' => false,
        'platform' => false,
        'pricing' => false,
        'supported_entities' => false,
        'supports_export' => false,
        'supports_import' => false,
        'supports_oauth' => false,
        'version' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'author' => 'author',
        'changelog' => 'changelog',
        'config_field_names' => 'config_field_names',
        'config_fields' => 'config_fields',
        'display_name' => 'display_name',
        'platform' => 'platform',
        'pricing' => 'pricing',
        'supported_entities' => 'supported_entities',
        'supports_export' => 'supports_export',
        'supports_import' => 'supports_import',
        'supports_oauth' => 'supports_oauth',
        'version' => 'version'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'author' => 'setAuthor',
        'changelog' => 'setChangelog',
        'config_field_names' => 'setConfigFieldNames',
        'config_fields' => 'setConfigFields',
        'display_name' => 'setDisplayName',
        'platform' => 'setPlatform',
        'pricing' => 'setPricing',
        'supported_entities' => 'setSupportedEntities',
        'supports_export' => 'setSupportsExport',
        'supports_import' => 'setSupportsImport',
        'supports_oauth' => 'setSupportsOauth',
        'version' => 'setVersion'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'author' => 'getAuthor',
        'changelog' => 'getChangelog',
        'config_field_names' => 'getConfigFieldNames',
        'config_fields' => 'getConfigFields',
        'display_name' => 'getDisplayName',
        'platform' => 'getPlatform',
        'pricing' => 'getPricing',
        'supported_entities' => 'getSupportedEntities',
        'supports_export' => 'getSupportsExport',
        'supports_import' => 'getSupportsImport',
        'supports_oauth' => 'getSupportsOauth',
        'version' => 'getVersion'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('author', $data ?? [], null);
        $this->setIfExists('changelog', $data ?? [], null);
        $this->setIfExists('config_field_names', $data ?? [], null);
        $this->setIfExists('config_fields', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('platform', $data ?? [], null);
        $this->setIfExists('pricing', $data ?? [], null);
        $this->setIfExists('supported_entities', $data ?? [], null);
        $this->setIfExists('supports_export', $data ?? [], null);
        $this->setIfExists('supports_import', $data ?? [], null);
        $this->setIfExists('supports_oauth', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['author'] === null) {
            $invalidProperties[] = "'author' can't be null";
        }
        if ($this->container['changelog'] === null) {
            $invalidProperties[] = "'changelog' can't be null";
        }
        if ($this->container['config_field_names'] === null) {
            $invalidProperties[] = "'config_field_names' can't be null";
        }
        if ($this->container['config_fields'] === null) {
            $invalidProperties[] = "'config_fields' can't be null";
        }
        if ($this->container['display_name'] === null) {
            $invalidProperties[] = "'display_name' can't be null";
        }
        if ($this->container['platform'] === null) {
            $invalidProperties[] = "'platform' can't be null";
        }
        if ($this->container['pricing'] === null) {
            $invalidProperties[] = "'pricing' can't be null";
        }
        if ($this->container['supported_entities'] === null) {
            $invalidProperties[] = "'supported_entities' can't be null";
        }
        if ($this->container['supports_export'] === null) {
            $invalidProperties[] = "'supports_export' can't be null";
        }
        if ($this->container['supports_import'] === null) {
            $invalidProperties[] = "'supports_import' can't be null";
        }
        if ($this->container['supports_oauth'] === null) {
            $invalidProperties[] = "'supports_oauth' can't be null";
        }
        if ($this->container['version'] === null) {
            $invalidProperties[] = "'version' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param string $author author
     *
     * @return self
     */
    public function setAuthor($author)
    {
        if (is_null($author)) {
            throw new \InvalidArgumentException('non-nullable author cannot be null');
        }
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets changelog
     *
     * @return \OpenAPI\Client\Model\ChangelogEntry[]
     */
    public function getChangelog()
    {
        return $this->container['changelog'];
    }

    /**
     * Sets changelog
     *
     * @param \OpenAPI\Client\Model\ChangelogEntry[] $changelog changelog
     *
     * @return self
     */
    public function setChangelog($changelog)
    {
        if (is_null($changelog)) {
            throw new \InvalidArgumentException('non-nullable changelog cannot be null');
        }
        $this->container['changelog'] = $changelog;

        return $this;
    }

    /**
     * Gets config_field_names
     *
     * @return string[]
     */
    public function getConfigFieldNames()
    {
        return $this->container['config_field_names'];
    }

    /**
     * Sets config_field_names
     *
     * @param string[] $config_field_names config_field_names
     *
     * @return self
     */
    public function setConfigFieldNames($config_field_names)
    {
        if (is_null($config_field_names)) {
            throw new \InvalidArgumentException('non-nullable config_field_names cannot be null');
        }
        $this->container['config_field_names'] = $config_field_names;

        return $this;
    }

    /**
     * Gets config_fields
     *
     * @return \OpenAPI\Client\Model\ConfigFieldInfo[]
     */
    public function getConfigFields()
    {
        return $this->container['config_fields'];
    }

    /**
     * Sets config_fields
     *
     * @param \OpenAPI\Client\Model\ConfigFieldInfo[] $config_fields config_fields
     *
     * @return self
     */
    public function setConfigFields($config_fields)
    {
        if (is_null($config_fields)) {
            throw new \InvalidArgumentException('non-nullable config_fields cannot be null');
        }
        $this->container['config_fields'] = $config_fields;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string $display_name display_name
     *
     * @return self
     */
    public function setDisplayName($display_name)
    {
        if (is_null($display_name)) {
            throw new \InvalidArgumentException('non-nullable display_name cannot be null');
        }
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets platform
     *
     * @return string
     */
    public function getPlatform()
    {
        return $this->container['platform'];
    }

    /**
     * Sets platform
     *
     * @param string $platform platform
     *
     * @return self
     */
    public function setPlatform($platform)
    {
        if (is_null($platform)) {
            throw new \InvalidArgumentException('non-nullable platform cannot be null');
        }
        $this->container['platform'] = $platform;

        return $this;
    }

    /**
     * Gets pricing
     *
     * @return \OpenAPI\Client\Model\PluginPricing
     */
    public function getPricing()
    {
        return $this->container['pricing'];
    }

    /**
     * Sets pricing
     *
     * @param \OpenAPI\Client\Model\PluginPricing $pricing pricing
     *
     * @return self
     */
    public function setPricing($pricing)
    {
        if (is_null($pricing)) {
            throw new \InvalidArgumentException('non-nullable pricing cannot be null');
        }
        $this->container['pricing'] = $pricing;

        return $this;
    }

    /**
     * Gets supported_entities
     *
     * @return string[]
     */
    public function getSupportedEntities()
    {
        return $this->container['supported_entities'];
    }

    /**
     * Sets supported_entities
     *
     * @param string[] $supported_entities supported_entities
     *
     * @return self
     */
    public function setSupportedEntities($supported_entities)
    {
        if (is_null($supported_entities)) {
            throw new \InvalidArgumentException('non-nullable supported_entities cannot be null');
        }
        $this->container['supported_entities'] = $supported_entities;

        return $this;
    }

    /**
     * Gets supports_export
     *
     * @return bool
     */
    public function getSupportsExport()
    {
        return $this->container['supports_export'];
    }

    /**
     * Sets supports_export
     *
     * @param bool $supports_export supports_export
     *
     * @return self
     */
    public function setSupportsExport($supports_export)
    {
        if (is_null($supports_export)) {
            throw new \InvalidArgumentException('non-nullable supports_export cannot be null');
        }
        $this->container['supports_export'] = $supports_export;

        return $this;
    }

    /**
     * Gets supports_import
     *
     * @return bool
     */
    public function getSupportsImport()
    {
        return $this->container['supports_import'];
    }

    /**
     * Sets supports_import
     *
     * @param bool $supports_import supports_import
     *
     * @return self
     */
    public function setSupportsImport($supports_import)
    {
        if (is_null($supports_import)) {
            throw new \InvalidArgumentException('non-nullable supports_import cannot be null');
        }
        $this->container['supports_import'] = $supports_import;

        return $this;
    }

    /**
     * Gets supports_oauth
     *
     * @return bool
     */
    public function getSupportsOauth()
    {
        return $this->container['supports_oauth'];
    }

    /**
     * Sets supports_oauth
     *
     * @param bool $supports_oauth supports_oauth
     *
     * @return self
     */
    public function setSupportsOauth($supports_oauth)
    {
        if (is_null($supports_oauth)) {
            throw new \InvalidArgumentException('non-nullable supports_oauth cannot be null');
        }
        $this->container['supports_oauth'] = $supports_oauth;

        return $this;
    }

    /**
     * Gets version
     *
     * @return string
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param string $version version
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


