<?php
/**
 * ShippingRate
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ShippingRate Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShippingRate implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ShippingRate';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'breakdown' => 'string',
        'carrier' => 'string',
        'cross_border_surcharge' => 'string',
        'destination_country' => 'string',
        'estimated_days' => 'int',
        'from_api' => 'bool',
        'insured_value' => 'string',
        'island_surcharge' => 'string',
        'origin_country' => 'string',
        'rate' => 'string',
        'service' => 'string',
        'volume_discount' => 'string',
        'weight_kg' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'breakdown' => null,
        'carrier' => null,
        'cross_border_surcharge' => null,
        'destination_country' => null,
        'estimated_days' => 'int32',
        'from_api' => null,
        'insured_value' => null,
        'island_surcharge' => null,
        'origin_country' => null,
        'rate' => null,
        'service' => null,
        'volume_discount' => null,
        'weight_kg' => 'double'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'breakdown' => true,
        'carrier' => false,
        'cross_border_surcharge' => true,
        'destination_country' => false,
        'estimated_days' => true,
        'from_api' => false,
        'insured_value' => true,
        'island_surcharge' => true,
        'origin_country' => false,
        'rate' => false,
        'service' => false,
        'volume_discount' => true,
        'weight_kg' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'breakdown' => 'breakdown',
        'carrier' => 'carrier',
        'cross_border_surcharge' => 'cross_border_surcharge',
        'destination_country' => 'destination_country',
        'estimated_days' => 'estimated_days',
        'from_api' => 'from_api',
        'insured_value' => 'insured_value',
        'island_surcharge' => 'island_surcharge',
        'origin_country' => 'origin_country',
        'rate' => 'rate',
        'service' => 'service',
        'volume_discount' => 'volume_discount',
        'weight_kg' => 'weight_kg'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'breakdown' => 'setBreakdown',
        'carrier' => 'setCarrier',
        'cross_border_surcharge' => 'setCrossBorderSurcharge',
        'destination_country' => 'setDestinationCountry',
        'estimated_days' => 'setEstimatedDays',
        'from_api' => 'setFromApi',
        'insured_value' => 'setInsuredValue',
        'island_surcharge' => 'setIslandSurcharge',
        'origin_country' => 'setOriginCountry',
        'rate' => 'setRate',
        'service' => 'setService',
        'volume_discount' => 'setVolumeDiscount',
        'weight_kg' => 'setWeightKg'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'breakdown' => 'getBreakdown',
        'carrier' => 'getCarrier',
        'cross_border_surcharge' => 'getCrossBorderSurcharge',
        'destination_country' => 'getDestinationCountry',
        'estimated_days' => 'getEstimatedDays',
        'from_api' => 'getFromApi',
        'insured_value' => 'getInsuredValue',
        'island_surcharge' => 'getIslandSurcharge',
        'origin_country' => 'getOriginCountry',
        'rate' => 'getRate',
        'service' => 'getService',
        'volume_discount' => 'getVolumeDiscount',
        'weight_kg' => 'getWeightKg'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('breakdown', $data ?? [], null);
        $this->setIfExists('carrier', $data ?? [], null);
        $this->setIfExists('cross_border_surcharge', $data ?? [], null);
        $this->setIfExists('destination_country', $data ?? [], null);
        $this->setIfExists('estimated_days', $data ?? [], null);
        $this->setIfExists('from_api', $data ?? [], null);
        $this->setIfExists('insured_value', $data ?? [], null);
        $this->setIfExists('island_surcharge', $data ?? [], null);
        $this->setIfExists('origin_country', $data ?? [], null);
        $this->setIfExists('rate', $data ?? [], null);
        $this->setIfExists('service', $data ?? [], null);
        $this->setIfExists('volume_discount', $data ?? [], null);
        $this->setIfExists('weight_kg', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['carrier'] === null) {
            $invalidProperties[] = "'carrier' can't be null";
        }
        if ($this->container['destination_country'] === null) {
            $invalidProperties[] = "'destination_country' can't be null";
        }
        if (!is_null($this->container['estimated_days']) && ($this->container['estimated_days'] < 0)) {
            $invalidProperties[] = "invalid value for 'estimated_days', must be bigger than or equal to 0.";
        }

        if ($this->container['from_api'] === null) {
            $invalidProperties[] = "'from_api' can't be null";
        }
        if ($this->container['origin_country'] === null) {
            $invalidProperties[] = "'origin_country' can't be null";
        }
        if ($this->container['rate'] === null) {
            $invalidProperties[] = "'rate' can't be null";
        }
        if ($this->container['service'] === null) {
            $invalidProperties[] = "'service' can't be null";
        }
        if ($this->container['weight_kg'] === null) {
            $invalidProperties[] = "'weight_kg' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets breakdown
     *
     * @return string|null
     */
    public function getBreakdown()
    {
        return $this->container['breakdown'];
    }

    /**
     * Sets breakdown
     *
     * @param string|null $breakdown breakdown
     *
     * @return self
     */
    public function setBreakdown($breakdown)
    {
        if (is_null($breakdown)) {
            array_push($this->openAPINullablesSetToNull, 'breakdown');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('breakdown', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['breakdown'] = $breakdown;

        return $this;
    }

    /**
     * Gets carrier
     *
     * @return string
     */
    public function getCarrier()
    {
        return $this->container['carrier'];
    }

    /**
     * Sets carrier
     *
     * @param string $carrier carrier
     *
     * @return self
     */
    public function setCarrier($carrier)
    {
        if (is_null($carrier)) {
            throw new \InvalidArgumentException('non-nullable carrier cannot be null');
        }
        $this->container['carrier'] = $carrier;

        return $this;
    }

    /**
     * Gets cross_border_surcharge
     *
     * @return string|null
     */
    public function getCrossBorderSurcharge()
    {
        return $this->container['cross_border_surcharge'];
    }

    /**
     * Sets cross_border_surcharge
     *
     * @param string|null $cross_border_surcharge cross_border_surcharge
     *
     * @return self
     */
    public function setCrossBorderSurcharge($cross_border_surcharge)
    {
        if (is_null($cross_border_surcharge)) {
            array_push($this->openAPINullablesSetToNull, 'cross_border_surcharge');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cross_border_surcharge', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cross_border_surcharge'] = $cross_border_surcharge;

        return $this;
    }

    /**
     * Gets destination_country
     *
     * @return string
     */
    public function getDestinationCountry()
    {
        return $this->container['destination_country'];
    }

    /**
     * Sets destination_country
     *
     * @param string $destination_country ISO-2 code of destination country.
     *
     * @return self
     */
    public function setDestinationCountry($destination_country)
    {
        if (is_null($destination_country)) {
            throw new \InvalidArgumentException('non-nullable destination_country cannot be null');
        }
        $this->container['destination_country'] = $destination_country;

        return $this;
    }

    /**
     * Gets estimated_days
     *
     * @return int|null
     */
    public function getEstimatedDays()
    {
        return $this->container['estimated_days'];
    }

    /**
     * Sets estimated_days
     *
     * @param int|null $estimated_days estimated_days
     *
     * @return self
     */
    public function setEstimatedDays($estimated_days)
    {
        if (is_null($estimated_days)) {
            array_push($this->openAPINullablesSetToNull, 'estimated_days');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('estimated_days', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($estimated_days) && ($estimated_days < 0)) {
            throw new \InvalidArgumentException('invalid value for $estimated_days when calling ShippingRate., must be bigger than or equal to 0.');
        }

        $this->container['estimated_days'] = $estimated_days;

        return $this;
    }

    /**
     * Gets from_api
     *
     * @return bool
     */
    public function getFromApi()
    {
        return $this->container['from_api'];
    }

    /**
     * Sets from_api
     *
     * @param bool $from_api True when the rate was obtained via an API call rather than calculation.
     *
     * @return self
     */
    public function setFromApi($from_api)
    {
        if (is_null($from_api)) {
            throw new \InvalidArgumentException('non-nullable from_api cannot be null');
        }
        $this->container['from_api'] = $from_api;

        return $this;
    }

    /**
     * Gets insured_value
     *
     * @return string|null
     */
    public function getInsuredValue()
    {
        return $this->container['insured_value'];
    }

    /**
     * Sets insured_value
     *
     * @param string|null $insured_value insured_value
     *
     * @return self
     */
    public function setInsuredValue($insured_value)
    {
        if (is_null($insured_value)) {
            array_push($this->openAPINullablesSetToNull, 'insured_value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('insured_value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['insured_value'] = $insured_value;

        return $this;
    }

    /**
     * Gets island_surcharge
     *
     * @return string|null
     */
    public function getIslandSurcharge()
    {
        return $this->container['island_surcharge'];
    }

    /**
     * Sets island_surcharge
     *
     * @param string|null $island_surcharge island_surcharge
     *
     * @return self
     */
    public function setIslandSurcharge($island_surcharge)
    {
        if (is_null($island_surcharge)) {
            array_push($this->openAPINullablesSetToNull, 'island_surcharge');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('island_surcharge', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['island_surcharge'] = $island_surcharge;

        return $this;
    }

    /**
     * Gets origin_country
     *
     * @return string
     */
    public function getOriginCountry()
    {
        return $this->container['origin_country'];
    }

    /**
     * Sets origin_country
     *
     * @param string $origin_country ISO-2 code of origin country.
     *
     * @return self
     */
    public function setOriginCountry($origin_country)
    {
        if (is_null($origin_country)) {
            throw new \InvalidArgumentException('non-nullable origin_country cannot be null');
        }
        $this->container['origin_country'] = $origin_country;

        return $this;
    }

    /**
     * Gets rate
     *
     * @return string
     */
    public function getRate()
    {
        return $this->container['rate'];
    }

    /**
     * Sets rate
     *
     * @param string $rate rate
     *
     * @return self
     */
    public function setRate($rate)
    {
        if (is_null($rate)) {
            throw new \InvalidArgumentException('non-nullable rate cannot be null');
        }
        $this->container['rate'] = $rate;

        return $this;
    }

    /**
     * Gets service
     *
     * @return string
     */
    public function getService()
    {
        return $this->container['service'];
    }

    /**
     * Sets service
     *
     * @param string $service service
     *
     * @return self
     */
    public function setService($service)
    {
        if (is_null($service)) {
            throw new \InvalidArgumentException('non-nullable service cannot be null');
        }
        $this->container['service'] = $service;

        return $this;
    }

    /**
     * Gets volume_discount
     *
     * @return string|null
     */
    public function getVolumeDiscount()
    {
        return $this->container['volume_discount'];
    }

    /**
     * Sets volume_discount
     *
     * @param string|null $volume_discount volume_discount
     *
     * @return self
     */
    public function setVolumeDiscount($volume_discount)
    {
        if (is_null($volume_discount)) {
            array_push($this->openAPINullablesSetToNull, 'volume_discount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('volume_discount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['volume_discount'] = $volume_discount;

        return $this;
    }

    /**
     * Gets weight_kg
     *
     * @return float
     */
    public function getWeightKg()
    {
        return $this->container['weight_kg'];
    }

    /**
     * Sets weight_kg
     *
     * @param float $weight_kg weight_kg
     *
     * @return self
     */
    public function setWeightKg($weight_kg)
    {
        if (is_null($weight_kg)) {
            throw new \InvalidArgumentException('non-nullable weight_kg cannot be null');
        }
        $this->container['weight_kg'] = $weight_kg;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


