<?php
/**
 * YearlyPayrollSummary
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * YearlyPayrollSummary Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class YearlyPayrollSummary implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'YearlyPayrollSummary';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'avg_employee_count' => 'int',
        'months' => '\OpenAPI\Client\Model\PayrollSummaryItem[]',
        'year' => 'int',
        'yearly_employer_cost' => 'string',
        'yearly_gross' => 'string',
        'yearly_net' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'avg_employee_count' => 'int32',
        'months' => null,
        'year' => 'int32',
        'yearly_employer_cost' => null,
        'yearly_gross' => null,
        'yearly_net' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'avg_employee_count' => false,
        'months' => false,
        'year' => false,
        'yearly_employer_cost' => false,
        'yearly_gross' => false,
        'yearly_net' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'avg_employee_count' => 'avg_employee_count',
        'months' => 'months',
        'year' => 'year',
        'yearly_employer_cost' => 'yearly_employer_cost',
        'yearly_gross' => 'yearly_gross',
        'yearly_net' => 'yearly_net'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'avg_employee_count' => 'setAvgEmployeeCount',
        'months' => 'setMonths',
        'year' => 'setYear',
        'yearly_employer_cost' => 'setYearlyEmployerCost',
        'yearly_gross' => 'setYearlyGross',
        'yearly_net' => 'setYearlyNet'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'avg_employee_count' => 'getAvgEmployeeCount',
        'months' => 'getMonths',
        'year' => 'getYear',
        'yearly_employer_cost' => 'getYearlyEmployerCost',
        'yearly_gross' => 'getYearlyGross',
        'yearly_net' => 'getYearlyNet'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('avg_employee_count', $data ?? [], null);
        $this->setIfExists('months', $data ?? [], null);
        $this->setIfExists('year', $data ?? [], null);
        $this->setIfExists('yearly_employer_cost', $data ?? [], null);
        $this->setIfExists('yearly_gross', $data ?? [], null);
        $this->setIfExists('yearly_net', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['avg_employee_count'] === null) {
            $invalidProperties[] = "'avg_employee_count' can't be null";
        }
        if ($this->container['months'] === null) {
            $invalidProperties[] = "'months' can't be null";
        }
        if ($this->container['year'] === null) {
            $invalidProperties[] = "'year' can't be null";
        }
        if ($this->container['yearly_employer_cost'] === null) {
            $invalidProperties[] = "'yearly_employer_cost' can't be null";
        }
        if ($this->container['yearly_gross'] === null) {
            $invalidProperties[] = "'yearly_gross' can't be null";
        }
        if ($this->container['yearly_net'] === null) {
            $invalidProperties[] = "'yearly_net' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets avg_employee_count
     *
     * @return int
     */
    public function getAvgEmployeeCount()
    {
        return $this->container['avg_employee_count'];
    }

    /**
     * Sets avg_employee_count
     *
     * @param int $avg_employee_count avg_employee_count
     *
     * @return self
     */
    public function setAvgEmployeeCount($avg_employee_count)
    {
        if (is_null($avg_employee_count)) {
            throw new \InvalidArgumentException('non-nullable avg_employee_count cannot be null');
        }
        $this->container['avg_employee_count'] = $avg_employee_count;

        return $this;
    }

    /**
     * Gets months
     *
     * @return \OpenAPI\Client\Model\PayrollSummaryItem[]
     */
    public function getMonths()
    {
        return $this->container['months'];
    }

    /**
     * Sets months
     *
     * @param \OpenAPI\Client\Model\PayrollSummaryItem[] $months months
     *
     * @return self
     */
    public function setMonths($months)
    {
        if (is_null($months)) {
            throw new \InvalidArgumentException('non-nullable months cannot be null');
        }
        $this->container['months'] = $months;

        return $this;
    }

    /**
     * Gets year
     *
     * @return int
     */
    public function getYear()
    {
        return $this->container['year'];
    }

    /**
     * Sets year
     *
     * @param int $year year
     *
     * @return self
     */
    public function setYear($year)
    {
        if (is_null($year)) {
            throw new \InvalidArgumentException('non-nullable year cannot be null');
        }
        $this->container['year'] = $year;

        return $this;
    }

    /**
     * Gets yearly_employer_cost
     *
     * @return string
     */
    public function getYearlyEmployerCost()
    {
        return $this->container['yearly_employer_cost'];
    }

    /**
     * Sets yearly_employer_cost
     *
     * @param string $yearly_employer_cost yearly_employer_cost
     *
     * @return self
     */
    public function setYearlyEmployerCost($yearly_employer_cost)
    {
        if (is_null($yearly_employer_cost)) {
            throw new \InvalidArgumentException('non-nullable yearly_employer_cost cannot be null');
        }
        $this->container['yearly_employer_cost'] = $yearly_employer_cost;

        return $this;
    }

    /**
     * Gets yearly_gross
     *
     * @return string
     */
    public function getYearlyGross()
    {
        return $this->container['yearly_gross'];
    }

    /**
     * Sets yearly_gross
     *
     * @param string $yearly_gross yearly_gross
     *
     * @return self
     */
    public function setYearlyGross($yearly_gross)
    {
        if (is_null($yearly_gross)) {
            throw new \InvalidArgumentException('non-nullable yearly_gross cannot be null');
        }
        $this->container['yearly_gross'] = $yearly_gross;

        return $this;
    }

    /**
     * Gets yearly_net
     *
     * @return string
     */
    public function getYearlyNet()
    {
        return $this->container['yearly_net'];
    }

    /**
     * Sets yearly_net
     *
     * @param string $yearly_net yearly_net
     *
     * @return self
     */
    public function setYearlyNet($yearly_net)
    {
        if (is_null($yearly_net)) {
            throw new \InvalidArgumentException('non-nullable yearly_net cannot be null');
        }
        $this->container['yearly_net'] = $yearly_net;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


